### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by AntonyGarand** [LewisArdern/bXSS#11]
Hey

I would like to add Discord support, so I am checking if you're open to the idea!
I would add a dependency on discord.js, and few relevant configuration options.

Thoughts?

**Comment by LewisArdern** [comment]
Please review the README.md on master, and let me know if you are happy with it https://github.com/LewisArdern/bXSS

**Comment by AntonyGarand** [comment]
Looks great!

**Comment by LewisArdern** [comment]
Thank you for your contribution 👍
