### ISSUE TITLE
Add configurable body-parser limit

### ISSUE THREAD

**Issue by inkz** [LewisArdern/bXSS#26]
Hello, recently I was testing a few apps with your utility and came across the fact that default **body-parser** limit (https://github.com/expressjs/body-parser#limit) is too small for handling some requests, especially while dealing with single-page applications.
I suggest adding **body-parser**'s limit option to config.

**Comment by LewisArdern** [comment]
Thanks for the contribution, makes a lot of sense to increase the body limit for full DOM capture for SPA
